# Predictive Modeling for Absenteeism

In [1]:
# Import the relevant libraries
import pandas as pd
import numpy as np

In [2]:
data_preprocessed = pd.read_csv('Absenteeism-preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          4  
1               31          0         1    0                          0  
2               31          0         0    0                          2  
3               24          0         2    0                          4  
4               30          0         2    1                          2

In [4]:
# Base line classification creation
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets =np.where(data_preprocessed['Absenteeism Time in Hours']>  
                    data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['Absenteeism Time in Hours'] = targets

In [8]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          1  
1               31          0         1    0                          0  
2               31          0         0    0                          0  
3               24          0         2    0                          1  
4               30          0         2    1                          0

In [9]:
targets.sum()/ targets.shape[0]

0.45571428571428574

In [10]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis=1)

In [11]:
data_with_targets is data_preprocessed

False

In [12]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  
0               30          0         2    1  
1               31          0         1    0  
2               31          0         0    0  
3               24          0         2    0  
4               30          0         2    1

In [13]:
#Selecting input for regression
data_with_targets.shape

(700, 14)

In [14]:
data_with_targets.iloc[:,0:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
5           0         0         0         1           10                2   
6           0         0         0         1            7                4   
7           0         0         0         1            7                4   
8           0         0         1         0            6                6   
9           0         0         0         1            7                0   
10          1         0         0         0            7                0   
11          1         0         0         0            7                1   
12          1         0         0         0            7                2   
13          1         0         0         0            7                2   
14          0         0         0         1            7                2   
15          1         0         0         0            7                4   
16          0         0         0         1            7                4   
17          0         0         1         0            7                0   
18          1         0         0         0            7                3   
19          0         0         0         1            5                4   
20          1         0         0         0           12                1   
21          1         0         0         0            3                6   
22          1         0         0         0           10                3   
23          0         0         0         1            8                4   
24          0         0         1         0            8                0   
25          0         0         0         1            8                0   
26          0         0         0         1            4                2   
27          0         0         0         1           12                1   
28          0         0         1         0            8                2   
29          0         0         0         1            8                4   
..        ...       ...       ...       ...          ...              ...   
670         0         0         0         1            4                1   
671         0         0         1         0            4                3   
672         1         0         0         0            4                3   
673         0         0         0         1            4                4   
674         0         0         0         1            7                3   
675         0         0         1         0            9                2   
676         0         0         0         1            9                2   
677         1         0         0         0            9                2   
678         0         0         0         1            9                2   
679         1         0         0         0           10                4   
680         0         0         0         1           10                4   
681         1         0         0         0           10                4   
682         0         0         1         0           11                0   
683         0         0         0         1           11                0   
684         0         0         0         1           11                0   
685         0         0         0         1            5                0   
686         1         0         0         0            5                1   
687         0         0         0         1            5                1   
688         0         0         0         0            5                1   
689         0         0         0         1            5                2   
6

In [15]:
data_with_targets.iloc[:,: -1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
5           0         0         0         1           10                2   
6           0         0         0         1            7                4   
7           0         0         0         1            7                4   
8           0         0         1         0            6                6   
9           0         0         0         1            7                0   
10          1         0         0         0            7                0   
11          1         0         0         0            7                1   
12          1         0         0         0            7                2   
13          1         0         0         0            7                2   
14          0         0         0         1            7                2   
15          1         0         0         0            7                4   
16          0         0         0         1            7                4   
17          0         0         1         0            7                0   
18          1         0         0         0            7                3   
19          0         0         0         1            5                4   
20          1         0         0         0           12                1   
21          1         0         0         0            3                6   
22          1         0         0         0           10                3   
23          0         0         0         1            8                4   
24          0         0         1         0            8                0   
25          0         0         0         1            8                0   
26          0         0         0         1            4                2   
27          0         0         0         1           12                1   
28          0         0         1         0            8                2   
29          0         0         0         1            8                4   
..        ...       ...       ...       ...          ...              ...   
670         0         0         0         1            4                1   
671         0         0         1         0            4                3   
672         1         0         0         0            4                3   
673         0         0         0         1            4                4   
674         0         0         0         1            7                3   
675         0         0         1         0            9                2   
676         0         0         0         1            9                2   
677         1         0         0         0            9                2   
678         0         0         0         1            9                2   
679         1         0         0         0           10                4   
680         0         0         0         1           10                4   
681         1         0         0         0           10                4   
682         0         0         1         0           11                0   
683         0         0         0         1           11                0   
684         0         0         0         1           11                0   
685         0         0         0         1            5                0   
686         1         0         0         0            5                1   
687         0         0         0         1            5                1   
688         0         0         0         0            5                1   
689         0         0         0         1            5                2   
6

In [16]:
unscaled_inputs = data_with_targets.iloc[:,: -1]

In [17]:
#from sklearn.preprocessing import StandardScaler
#absenteeism_scaler = StandardScaler()

In [18]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler = StandardScaler(copy,with_mean,with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self

    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [19]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children'], dtype=object)

In [20]:
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [21]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [22]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [23]:
absenteeism_scaler.fit(unscaled_inputs)

C:\Users\User\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)


CustomScaler(columns=['Month Value', 'Day of the Week', 'Transportation Expense', 'Distance to Work', 'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children'],
       copy=None, with_mean=None, with_std=None)

In [24]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


In [25]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1     0.030796        -0.800950   
1           0         0         0         0     0.030796        -0.800950   
2           0         0         0         1     0.030796        -0.232900   
3           1         0         0         0     0.030796         0.335149   
4           0         0         0         1     0.030796         0.335149   
5           0         0         0         1     0.929019        -0.232900   
6           0         0         0         1     0.030796         0.903199   
7           0         0         0         1     0.030796         0.903199   
8           0         0         1         0    -0.268611         2.039298   
9           0         0         0         1     0.030796        -1.368999   
10          1         0         0         0     0.030796        -1.368999   
11          1         0         0         0     0.030796        -0.800950   
12          1         0         0         0     0.030796        -0.232900   
13          1         0         0         0     0.030796        -0.232900   
14          0         0         0         1     0.030796        -0.232900   
15          1         0         0         0     0.030796         0.903199   
16          0         0         0         1     0.030796         0.903199   
17          0         0         1         0     0.030796        -1.368999   
18          1         0         0         0     0.030796         0.335149   
19          0         0         0         1    -0.568019         0.903199   
20          1         0         0         0     1.527833        -0.800950   
21          1         0         0         0    -1.166834         2.039298   
22          1         0         0         0     0.929019         0.335149   
23          0         0         0         1     0.330204         0.903199   
24          0         0         1         0     0.330204        -1.368999   
25          0         0         0         1     0.330204        -1.368999   
26          0         0         0         1    -0.867426        -0.232900   
27          0         0         0         1     1.527833        -0.800950   
28          0         0         1         0     0.330204        -0.232900   
29          0         0         0         1     0.330204         0.903199   
..        ...       ...       ...       ...          ...              ...   
670         0         0         0         1    -0.867426        -0.800950   
671         0         0         1         0    -0.867426         0.335149   
672         1         0         0         0    -0.867426         0.335149   
673         0         0         0         1    -0.867426         0.903199   
674         0         0         0         1     0.030796         0.335149   
675         0         0         1         0     0.629611        -0.232900   
676         0         0         0         1     0.629611        -0.232900   
677         1         0         0         0     0.629611        -0.232900   
678         0         0         0         1     0.629611        -0.232900   
679         1         0         0         0     0.929019         0.903199   
680         0         0         0         1     0.929019         0.903199   
681         1         0         0         0     0.929019         0.903199   
682         0         0         1         0     1.228426        -1.368999   
683         0         0         0         1     1.228426        -1.368999   
684         0         0         0         1     1.228426        -1.368999   
685         0         0         0         1    -0.568019        -1.368999   
686         1         0         0         0    -0.568019        -0.800950   
687         0         0         0         1    -0.568019        -0.800950   
688         0         0         0         0    -0.568019        -0.800950   
689         0         0         0         1    -0.568019        -0.232900   
6

In [26]:
scaled_inputs.shape

(700, 13)

In [27]:
# Split the data into train and test
from sklearn.model_selection import train_test_split

In [28]:
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
 270         1         0         0         0    -0.568019        -1.368999   
 555         1         0         0         0    -0.568019         0.903199   
 106         0         0         0         1     0.929019        -1.368999   
 388         0         0         0         1    -1.466241        -0.232900   
 1           0         0         0         0     0.030796        -0.800950   
 415         0         0         0         1     0.929019        -0.232900   
 670         0         0         0         1    -0.867426        -0.800950   
 611         1         0         0         0    -1.466241        -1.368999   
 141         0         0         0         1     1.228426        -0.232900   
 416         0         0         0         1     0.929019        -0.232900   
 500         0         0         0         1     0.330204        -0.232900   
 184         0         0         0         1    -0.268611       

In [29]:
X_train, X_test, y_train, y_test=train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

C:\Users\User\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [30]:
print (X_train.shape, y_train.shape)

(560, 13) (560,)


In [31]:
print (X_test.shape, y_test.shape)

(140, 13) (140,)


In [32]:
#Logistic regression with sklearn 
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [33]:
reg = LogisticRegression()

In [34]:
reg.fit(X_train, y_train)

C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [35]:
reg.score(X_train, y_train)

0.775

In [36]:
#Manual Check
model_outputs = reg.predict(X_train)
model_outputs

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [37]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [38]:
model_outputs == y_train

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [39]:
np.sum(model_outputs == y_train)

434

In [40]:
model_outputs.shape[0]

560

In [41]:
np.sum(model_outputs == y_train) / model_outputs.shape[0]

0.775

In [42]:
#Finding intercept and coefficients
reg.intercept_

array([-1.44858081])

In [43]:
reg.coef_

array([[ 2.63259611,  0.86935993,  2.81289745,  0.65092627,  0.00723232,
        -0.07199168,  0.49781562, -0.03874266, -0.12321956, -0.02108164,
         0.26813826, -0.23006247,  0.37360592]])

In [44]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children'], dtype=object)

In [45]:
feature_name = unscaled_inputs.columns.values

In [46]:
summary_table = pd.DataFrame (columns=['Feature name'], data = feature_name)

summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table

Feature name  Coefficient
0                  Reason_1     2.632596
1                  Reason_2     0.869360
2                  Reason_3     2.812897
3                  Reason_4     0.650926
4               Month Value     0.007232
5           Day of the Week    -0.071992
6    Transportation Expense     0.497816
7          Distance to Work    -0.038743
8                       Age    -0.123220
9   Daily Work Load Average    -0.021082
10          Body Mass Index     0.268138
11                Education    -0.230062
12                 Children     0.373606

In [47]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summay_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
1                  Reason_1     2.632596
2                  Reason_2     0.869360
3                  Reason_3     2.812897
4                  Reason_4     0.650926
5               Month Value     0.007232
6           Day of the Week    -0.071992
7    Transportation Expense     0.497816
8          Distance to Work    -0.038743
9                       Age    -0.123220
10  Daily Work Load Average    -0.021082
11          Body Mass Index     0.268138
12                Education    -0.230062
13                 Children     0.373606
0                 Intercept    -1.448581

In [48]:
summary_table['Odd ratio'] = np.exp(summary_table.Coefficient)

In [49]:
summary_table 

Feature name  Coefficient  Odd ratio
1                  Reason_1     2.632596  13.909835
2                  Reason_2     0.869360   2.385384
3                  Reason_3     2.812897  16.658114
4                  Reason_4     0.650926   1.917316
5               Month Value     0.007232   1.007259
6           Day of the Week    -0.071992   0.930539
7    Transportation Expense     0.497816   1.645124
8          Distance to Work    -0.038743   0.961998
9                       Age    -0.123220   0.884070
10  Daily Work Load Average    -0.021082   0.979139
11          Body Mass Index     0.268138   1.307528
12                Education    -0.230062   0.794484
13                 Children     0.373606   1.452964
0                 Intercept    -1.448581   0.234903

In [50]:
summary_table.sort_values('Odd ratio', ascending=False)

Feature name  Coefficient  Odd ratio
3                  Reason_3     2.812897  16.658114
1                  Reason_1     2.632596  13.909835
2                  Reason_2     0.869360   2.385384
4                  Reason_4     0.650926   1.917316
7    Transportation Expense     0.497816   1.645124
13                 Children     0.373606   1.452964
11          Body Mass Index     0.268138   1.307528
5               Month Value     0.007232   1.007259
10  Daily Work Load Average    -0.021082   0.979139
8          Distance to Work    -0.038743   0.961998
6           Day of the Week    -0.071992   0.930539
9                       Age    -0.123220   0.884070
12                Education    -0.230062   0.794484
0                 Intercept    -1.448581   0.234903

In [52]:
#Test the model
reg.score(X_test, y_test)

0.7357142857142858

predicted_proba = reg.predict_proba(X_test)
predicted_proba

In [57]:
predicted_proba.shape

(140, 2)

In [58]:
predicted_proba[:,1]

array([0.22123841, 0.36746562, 0.50004073, 0.2089951 , 0.90917697,
       0.69301566, 0.77107214, 0.8859558 , 0.29549433, 0.22275347,
       0.60483662, 0.73858908, 0.90619582, 0.34200406, 0.74793341,
       0.40182971, 0.5876329 , 0.55788212, 0.68102628, 0.92943054,
       0.31492142, 0.21583614, 0.56698637, 0.54895219, 0.79581917,
       0.29599005, 0.44955041, 0.11650185, 0.71867643, 0.22283802,
       0.39170243, 0.77004683, 0.66038918, 0.60501965, 0.21583614,
       0.55420036, 0.30950994, 0.73126219, 0.4762001 , 0.53951185,
       0.23294667, 0.43933879, 0.29219299, 0.38449721, 0.83762964,
       0.61556479, 0.73604752, 0.23015421, 0.23219654, 0.20045226,
       0.49883448, 0.25661573, 0.67030132, 0.22865307, 0.83616221,
       0.40858324, 0.93437215, 0.28932031, 0.31364181, 0.30863997,
       0.69642044, 0.64430772, 0.28256538, 0.80449431, 0.3206113 ,
       0.2233284 , 0.07984234, 0.2970576 , 0.70680172, 0.34453101,
       0.30245977, 0.27141705, 0.87740585, 0.4721832 , 0.58892